SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE sentiment_analysis_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    text_content TEXT NOT NULL,
    polarity DECIMAL(5, 2) NOT NULL,
    subjectivity DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=0;

INSERT INTO sentiment_analysis_results (text_content, polarity, subjectivity) VALUES
    ("Rome, the eternal city, is a breathtaking blend of ancient history and modern culture. Walking through its cobblestone streets, one encounters majestic ruins like the Colosseum and the Roman Forum, which evoke a sense of awe and wonder. The vibrant street life, with bustling markets and cozy cafes, creates an atmosphere of warmth and conviviality. As the sun sets, the city lights up, casting a magical glow over iconic landmarks like the Trevi Fountain and St. Peter''s Basilica. Despite its busy urban life, Rome offers serene escapes in its lush parks and tranquil piazzas, making it a city of endless charm and inspiration.", 0.18, 0.45),
    ("Paris, the city of lights, exudes romance and elegance. Its iconic landmarks, such as the Eiffel Tower and the Louvre Museum, draw millions of visitors who marvel at their beauty and grandeur. Strolling along the Seine River, one can admire the charming bridges and historic architecture that define the city''s aesthetic. The lively cafes and bistros, offering exquisite French cuisine, contribute to a vibrant social scene. Parisian neighborhoods like Montmartre and Le Marais are rich with artistic and cultural heritage, creating a unique atmosphere of creativity and inspiration. Paris, with its timeless charm, continues to enchant and inspire.", 0.29, 0.52),
    ("New York City, often called the Big Apple, is a vibrant metropolis pulsating with energy and diversity. The towering skyscrapers, such as the Empire State Building and One World Trade Center, symbolize ambition and innovation. Walking through the bustling streets of Manhattan, one experiences a whirlwind of cultures, cuisines, and artistic expressions. Central Park offers a serene oasis amidst the urban hustle, while Times Square dazzles with its bright lights and constant activity. From the rich history of Ellis Island to the cutting-edge trends in Brooklyn, New York City embodies a dynamic spirit that captivates and inspires all who visit.", 0.13, 0.37),
    ("Dubai, a city of innovation and luxury, is a dazzling metropolis in the heart of the desert. Known for its futuristic skyline, featuring landmarks like the Burj Khalifa and the Burj Al Arab, Dubai epitomizes modern architectural marvels. The bustling souks and extravagant malls, such as the Dubai Mall, offer a blend of traditional and contemporary shopping experiences. The Palm Jumeirah and its luxurious resorts provide a serene escape with stunning views of the Arabian Gulf. Dubai''s vibrant nightlife and world-class dining add to its allure, making it a dynamic and captivating destination that embodies ambition and opulence.", 0.25, 0.58),
    ("London, a city rich in history and culture, stands as a global metropolis where tradition meets modernity. Iconic landmarks such as Big Ben, the Tower of London, and Buckingham Palace reflect its storied past, while the Shard and the London Eye symbolize contemporary innovation. The city''s diverse neighborhoods, from the artistic vibes of Shoreditch to the elegance of Kensington, offer a myriad of experiences. London''s green spaces, like Hyde Park and Regent''s Park, provide tranquil retreats amidst the urban hustle. The vibrant theatre scene in the West End, along with world-renowned museums, contribute to London''s reputation as a cultural capital.", 0.10, 0.33);